# Terminal settings
set -g set-titles on
set -g set-titles-string "Tmux: #S (#W)"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Active pane
set -g pane-border-indicators "both"
set -g pane-border-lines "heavy"
set -g pane-border-status top
set -g pane-border-format " #{pane_index} "

# Status line configuration
set -g status-position top
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_flags "icon"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"

# vim tmux navigation
set -g @vim_navigator_mapping_left "C-h"
set -g @vim_navigator_mapping_right "C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"

# continuum-restore configuration
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim "session"
set -g @continuum-save-interval '5'
set -g @continuum-restore "on"

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
